### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by llamallamagirl** [oauth-io/oauth-js#87]
Hello-

This is not a code issue but a server issue. oauth.io is currently returning  Service Unavailable: Back-end server is at capacity Code 503. When do you think this can be addressed? I sent an email to support@ too.

Thank you!
Kristin

**Comment by thyb** [comment]
Thanks for the reporting and sorry for the inconvenience.
We saw your email support, we're working on this issue. 
We do our best to resolve this downtime as fast as possible.

**Comment by llamallamagirl** [comment]
Great, thank you!

-kristin

**Comment by thyb** [comment]
seems related with http://serverfault.com/questions/556621/aws-elb-apache2-503-service-unavailable-back-end-server-is-at-capacity

**Comment by thyb** [comment]
Resolved: The ELB health check was failing. We forced the test to pass to understand the real issue. The server was in a strange state (not crashed but not replying too) so `forever` had not automatically restart the server. We’ll add a backup instance in the load balancer in case the main instance enter again in the same state.

**Comment by llamallamagirl** [comment]
Thank you!

**Comment by chonbas** [comment]
It seems the service is down again. Any update?

**Comment by thyb** [comment]
We've just got a 4min downtime. It's a recurrence of the bug of yesterday... We already got the scripts to fix this issue quickly. We had planned the infrastructure upgrade (mentioned in my previous comment about adding backup instance to handle this case) for Sunday night (where the traffic is the lowest). We will do it tonight instead as this bug seem to have recurrence. The infrastructure upgrade should not impact the traffic. We'll also push the investigation to really understand the root cause of this crash which is still unknown. We keep an eye on the server status meanwhile it's not definitively fix. I'll give more update asap.
