### ISSUE TITLE
get request not forwarding twitter include_email parameter 

### ISSUE THREAD

**Issue by benlogan1981** [oauth-io/oauth-js#91]
I'm fairly sure that include_email=true as a parameter on the verify_credentials request is not making it's way through to Twitter. Quite possibly a server side issue on oauth.io?

/1.1/account/verify_credentials.json?include_email=true

**Comment by thyb** [comment]
Thanks for the error reporting !

It seems to happen since our last OAuth.io/oauthd 1.0 release which includes lots of dependencies upgrade. Unfortunately, we missed a breaking change from Restify which changed the behavior of `req.query()` (used for parsing query params in GET request).

I fixed this issue in https://github.com/oauth-io/oauthd/commit/b2ad616592883b2773b1489e374c65575e319913

We've released oauthd v1.0.1 and deployed the new version on oauth.io so it should work as normal now.

**Comment by benlogan1981** [comment]
Perfect, thanks again! 👍
